services:
  app:
    build: .
    container_name: app
    ports:
      - "7860:7860"
    volumes:
      - .:/code
    depends_on:
      - ollama
    env_file:
      - .env
    networks:
      - internal_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - internal_network

networks:
    internal_network:
        driver: bridge