version: '3.8'
services:
  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - ollama_server
    env_file:
      - .env
    networks:
      - internal_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:root/.ollama
    networks:
      - internal_network

networks:
    internal_network:
        driver: bridge